### ISSUE TITLE
`FindOne` methods should return error when not found

### ISSUE THREAD

**Issue by dripolles** [tyba/storable#7]
When we execute a `FindOne` method, we need to "double check" for an error and a not nil object
```go
foo, err := fooStore.FindOneById(id)
if err != nil {
    // do something with err
} else if foo == nil {
    // do something to address that foo was not found
}
```

It would be nice to have something like `NotFoundErr` that was returned as the error when `foo` is not found. This could make error management easier.

**Comment by dripolles** [comment]
This didn't get traction, so I'm closing it.

**Comment by mcuadros** [comment]
https://github.com/tyba/storable/blob/master/resultset.go#L42

Was made some weeks ago.
